export * as apiProdCategories from './productCategory'
export * as apiProducts from './product'
export * as apiUsers from './user'
export * as apiCoupons from './coupon'
export * as apiOrders from './order'