import { FaPhone } from 'react-icons/fa6'
import { LuBadgeCheck } from 'react-icons/lu'
import { MdEmail, MdLockOutline, MdDelete } from 'react-icons/md'
import { IoMenu } from 'react-icons/io5'
import { TfiHeadphone } from 'react-icons/tfi'
import { IoIosLaptop, IoIosArrowForward, IoMdArrowDropright, IoMdArrowDropdown } from 'react-icons/io'
import { IoKeyOutline, IoReturnDownBackOutline } from 'react-icons/io5'
import { CiCamera, CiEdit } from 'react-icons/ci'
import { BsPrinter, BsSpeaker } from 'react-icons/bs'
import { GiSmartphone, GiTablet, GiPositionMarker } from 'react-icons/gi'
import { PiTelevisionThin } from 'react-icons/pi'
import { SiAmericanexpress } from 'react-icons/si'
import { RxDashboard } from "react-icons/rx";
import { FaUserGroup } from "react-icons/fa6";
import {
   FaFileInvoiceDollar,
   FaProductHunt,
   FaEye,
   FaEyeSlash,
   FaShoppingCart,
   FaRegHeart,
   FaUserCircle,
   FaStar,
   FaStarHalfAlt,
   FaRegStar,
   FaRegEye,
   FaPhoneAlt,
   FaFacebook,
   FaTwitter,
   FaPinterest,
   FaGoogle,
   FaLinkedin,
   FaFlickr,
   FaCcVisa,
   FaCcMastercard,
   FaCcPaypal,
   FaCcDiscover,
   FaCcDinersClub,
   FaMinus,
   FaArrowLeft,
   FaShieldAlt,
   FaTruck,
   FaGift,
   FaReply,
   FaTty,
   FaCaretUp,
   FaChevronDown,
   FaSearch,
} from 'react-icons/fa'

const icons = {
   IoReturnDownBackOutline,
   FaSearch,
   MdDelete,
   CiEdit,
   IoMdArrowDropright,
   IoMdArrowDropdown,
   FaFileInvoiceDollar,
   FaProductHunt,
   FaUserGroup,
   RxDashboard,
   FaChevronDown,
   FaCaretUp,
   FaTty,
   FaReply,
   FaTruck,
   FaGift,
   FaShieldAlt,
   IoIosArrowForward,
   FaEye,
   FaEyeSlash,
   MdLockOutline,
   FaMinus,
   FaArrowLeft,
   SiAmericanexpress,
   FaCcVisa,
   FaCcMastercard,
   FaCcPaypal,
   FaCcDiscover,
   FaCcDinersClub,
   FaFacebook,
   FaTwitter,
   FaPinterest,
   FaGoogle,
   FaLinkedin,
   FaFlickr,
   GiPositionMarker,
   FaPhoneAlt,
   TfiHeadphone,
   IoIosLaptop,
   CiCamera,
   BsPrinter,
   BsSpeaker,
   GiSmartphone,
   GiTablet,
   PiTelevisionThin,
   FaPhone,
   MdEmail,
   FaRegHeart,
   FaShoppingCart,
   FaUserCircle,
   FaStar,
   FaStarHalfAlt,
   FaRegStar,
   FaRegEye,
   IoMenu,
   IoKeyOutline,
   LuBadgeCheck,
}
export default icons
