import { LuBadgeCheck } from 'react-icons/lu'
import { MdEmail, MdLockOutline, MdDelete, MdHistory } from 'react-icons/md'
import { TfiHeadphone } from 'react-icons/tfi'
import { IoIosLaptop, IoIosArrowForward, IoMdArrowDropright, IoMdArrowDropdown, IoMdClose } from 'react-icons/io'
import { IoKeyOutline, IoReturnDownBackOutline, IoMenu } from 'react-icons/io5'
import { CiCamera, CiEdit } from 'react-icons/ci'
import { BsPrinter, BsSpeaker, BsFillPersonFill, BsCartCheckFill } from 'react-icons/bs'
import { GiSmartphone, GiTablet, GiPositionMarker } from 'react-icons/gi'
import { PiTelevisionThin } from 'react-icons/pi'
import { SiAmericanexpress } from 'react-icons/si'
import { RxDashboard } from "react-icons/rx";
import { FaPhone, FaUserGroup, FaPlus } from "react-icons/fa6";
import { CgPlayListAdd } from "react-icons/cg";
import { BiLogOutCircle } from "react-icons/bi";
import { RiAdminLine } from "react-icons/ri";
import { ImProfile } from "react-icons/im";
import {
   FaHome,
   FaLock,
   FaFileInvoiceDollar,
   FaProductHunt,
   FaEye,
   FaEyeSlash,
   FaShoppingCart,
   FaRegHeart,
   FaUserCircle,
   FaStar,
   FaStarHalfAlt,
   FaRegStar,
   FaRegEye,
   FaPhoneAlt,
   FaFacebook,
   FaTwitter,
   FaPinterest,
   FaGoogle,
   FaLinkedin,
   FaFlickr,
   FaCcVisa,
   FaCcMastercard,
   FaCcPaypal,
   FaCcDiscover,
   FaCcDinersClub,
   FaMinus,
   FaArrowLeft,
   FaShieldAlt,
   FaTruck,
   FaGift,
   FaReply,
   FaTty,
   FaCaretUp,
   FaChevronDown,
   FaSearch,
   FaLongArrowAltRight,
} from 'react-icons/fa'

const icons = {
   FaHome,
   FaLongArrowAltRight,
   IoMdClose,
   BsCartCheckFill,
   FaLock,
   MdHistory,
   BsFillPersonFill,
   RiAdminLine,
   ImProfile,
   BiLogOutCircle,
   CgPlayListAdd,
   FaPlus,
   IoReturnDownBackOutline,
   FaSearch,
   MdDelete,
   CiEdit,
   IoMdArrowDropright,
   IoMdArrowDropdown,
   FaFileInvoiceDollar,
   FaProductHunt,
   FaUserGroup,
   RxDashboard,
   FaChevronDown,
   FaCaretUp,
   FaTty,
   FaReply,
   FaTruck,
   FaGift,
   FaShieldAlt,
   IoIosArrowForward,
   FaEye,
   FaEyeSlash,
   MdLockOutline,
   FaMinus,
   FaArrowLeft,
   SiAmericanexpress,
   FaCcVisa,
   FaCcMastercard,
   FaCcPaypal,
   FaCcDiscover,
   FaCcDinersClub,
   FaFacebook,
   FaTwitter,
   FaPinterest,
   FaGoogle,
   FaLinkedin,
   FaFlickr,
   GiPositionMarker,
   FaPhoneAlt,
   TfiHeadphone,
   IoIosLaptop,
   CiCamera,
   BsPrinter,
   BsSpeaker,
   GiSmartphone,
   GiTablet,
   PiTelevisionThin,
   FaPhone,
   MdEmail,
   FaRegHeart,
   FaShoppingCart,
   FaUserCircle,
   FaStar,
   FaStarHalfAlt,
   FaRegStar,
   FaRegEye,
   IoMenu,
   IoKeyOutline,
   LuBadgeCheck,
}
export default icons
